version: "3.9"
services:
  postgres-db:
    image: postgres
    restart: always
    container_name: oscar-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example-db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: